services:
  - type: private_service
    name: ollama-service
    env: docker
    plan: starter
    autoDeploy: false
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    ports:
      - 11434
